name: Infra Core
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.MONGODBATLAS_PUBLIC_KEY }}
  MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.MONGODBATLAS_PRIVATE_KEY }}

jobs:
  PlanProduction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: |
          terraform plan \
          -var="cloudflare_api_key=${{ secrets.CLOUDFLARE_API_KEY }}" \
          -var="cloudflare_account_email"=${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }} \
          -var="cloudflare_main_zone_id=${{ secrets.CLOUDFLARE_ZONE_ID }}" \
          -var="cloudflare_account_id=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" \
          -var="mongodbatlas_public_key=${{ secrets.MONGODBATLAS_PUBLIC_KEY }}" \
          -var="mongodbatlas_private_key=${{ secrets.MONGODBATLAS_PRIVATE_KEY }}" \
          -no-color -out tfplan

      - name: Publish Terraform Plan
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: upload
          path: |
            code.zip
            tfplan
            scraper_layer_content.zip

  ApplyProduction:
    needs: PlanProduction
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4

      - name: Move files from .upload directory to root
        run: |
          mv ./upload/* ./

      - name: Terraform apply
        run: |
          terraform apply -auto-approve tfplan
